"""Instruction Set DSL."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

class Instruction(BaseModel):
    """A deterministic instruction generated by the Planner."""
    agent_name: str = Field(..., description="The name of the agent to execute this instruction.")
    intent: str = Field(..., description="The capability/tool intent to execute.")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the tool.")
    description: Optional[str] = Field(default=None, description="Human-readable description of this step.")

class GraphUpdate(BaseModel):
    """The strongly typed Graph Update produced by the Planner."""
    thought: str = Field(default="", description="Reasoning about the current state of Working Memory, Discovered Entities, and what nodes need to be added to the graph.")
    next_plan: str = Field(default="", description="Explicitly states the next logical move based on Working Memory and the immediate results from the last step.")
    output_document_append: str = Field(default="", description="Content to append to the Continuous Output Workspace document.")
    memory_updates: Dict[str, Any] = Field(default_factory=dict, description="Structured facts extracted from recent observations to save in Working Memory.")
    new_tasks: List[Dict[str, Any]] = Field(default_factory=list, description="New tasks to add to the graph. Must include id, description, instruction_agent, instruction_intent, instruction_parameters, and dependencies.")
    is_task_complete: bool = Field(default=False, description="Set to true if the overarching goal is fully achieved and no further execution is needed.")
    final_response: Optional[str] = Field(default=None, description="The final text response to present to the user if is_task_complete is true.")
    render_actions: List[Dict[str, Any]] = Field(default_factory=list, description="Array of objects to render, e.g. [{'type': 'dataset', 'id': 'OBJ_17'}].")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional context or planning metadata.")
